gpu_id: 0
nodes:
  local:  {membind: 0, cpunodebind: 0}
  remote: {membind: 1, cpunodebind: 0}
  pmem:   {membind: 2, cpunodebind: 0}

ratios: [0.3, 0.7, 1.0, 1.5, 2.0]
workloads: [backprop] # backprop, bfs, fdtd2d, hotspot, nw, pathfinder
modes: [unmanaged, um] # unmanaged, um

um_profiles:
  - name: um_base
    pf: false
    ab: none
    pl: none
    rm: none
  - name: um_pf
    pf: true
    ab: none
    pl: none
    rm: none
  - name: um_ab_gpu0_pl_cpu
    pf: false
    ab: gpu0
    pl: cpu
    rm: none 
  - name: um_rm_gpu0
    pf: false
    ab: none
    pl: none
    rm: gpu0

